### ISSUE TITLE
Improve travis cfg

### ISSUE THREAD

**Issue by amerlyq** [albfan/ag.vim#24]
If I understand correctly, we can't make PR to add travis support into rking branch with no efforts?
Because it requires manual labour from rking itself.
However we could try to PR template configs and write issue with instructions?

Also, try to migrate your travis config to dockers (container) architecture, which runs much faster, but can't use sudo. Because `sudo` isn't actually necessary for this plugin testing.

**Comment by albfan** [comment]
I love docker so change it at your will.

For use travis rking just needs to login on travis with its github account and activate repo. But this is a custom testsuite so expect reluctant reactions proposing others to use it.

**Comment by amerlyq** [comment]
I think, it would be more fast for you to migrate `travis.yml` on your side.
Because while I will try it by myself, you will be spammed-out by broken builds:)

``` Yaml
sudo: false

addons:
  apt:
    packages:
    - vim
    - automake
    - pkg-config
    - libpcre3-dev
    - zlib1g-dev
    - liblzma-dev

before_install:
  - if [ ! -d "$HOME/ag" ]; then
    wget https://github.com/ggreer/the_silver_searcher/archive/master.zip;
    unzip master.zip && mv -vf the_silver_searcher-master ag;
    cd ag && ./build.sh && make install;
    fi

cache:
  directories:
  - $HOME/ag
```

Seems like it must be enough to run builds in dockers.
We build and cache ag, because it's not contained in approved sudo-less whitelist for travis/dockers.
However, if `make install` will work not as expected, you will need to add `export PATH="$HOME/ag:$PATH"`
Try it, please.

**Comment by albfan** [comment]
although sounds great, needing to compile ag is enough to refuse this change, meanwhile exist another solution which installs dependencies on OS side.

I would close this issue in the actual terms

**Comment by amerlyq** [comment]
My bad, I specified not full config, but only its part necessary to setup equivalent environment in dockers.
Therefore insert 'script:' section back into config, please.

**Comment by amerlyq** [comment]
About compiling `ag` -- I don't like it either. Currently building is necessary because no one added ag to white list of travis dockers packages. If someone will do it, we can simplify config much more.

Compiling thanks to `caching:` will be done only once in a while when dockers will be clearing cache. Therefore, as it will not be compiled on each commit, it's not that big deal -- especially as it takes dozen seconds at most. On other hands with dockers we have almost instant CI starting time and build status update, two times more system resources and newer underlying OS. Because current travis is not (and will not) upgrading sudo-required servers past Ubuntu 12.04. Only dockers will eventually do.

**Comment by amerlyq** [comment]
This reminds me about question I haven't asked yet.
For what purpose you use appveyor? Checking on windows?
I feel bad every time when look on all branches statuses and see only red crosses.
Is it possible to fix it or disable until fixed? Because currently overall status is irrelevant to actual code.
You may persist on lazy development and "don't fix until broken", but... it simply isn't nice, agree?

**Comment by amerlyq** [comment]
You erased my work by `push -f`. I'm too displeased, because I helped out to fix it.
Last state of travis.cfg:

``` Yaml
sudo: false

addons:
  apt:
    packages:
    - vim
    - automake
    - pkg-config
    - libpcre3-dev
    - zlib1g-dev
    - liblzma-dev

before_install:
  - if [ -d ./ag ]; then rm -rf ./ag; fi  # REM
  - if [ ! -d ./ag ]; then
    wget https://github.com/ggreer/the_silver_searcher/archive/master.zip;
    unzip master.zip && mv -vf the_silver_searcher-master ag; fi
  - if [ ! -f ./ag/ag ]; then
    (cd ./ag && ./build.sh)
    || (rm -rf ./ag; exit -1); fi
  - if [ ! -f ./ag/ag/ag- ]; then
    mv -v ./ag/ag{,-};
    printf '#!/bin/sh\nag- --noaffinity "$@"' > ./ag/ag;
    chmod +x ./ag/ag; fi
  - if ! hash ag >/dev/null 2>&1; then
    export PATH="$PWD/ag:$PATH"; fi

cache:
  directories:
  - $HOME/ag

script:
  - vim --version
  - ag --version
  - cd t && ./suite.sh --verbose --clean
```
